Tests
jocsakesley/raizama pull request #13
Opened 2021-02-22 18:30 UTC by jocsakesley

2021-02-22 21:18 UTC, cuducos requested changes

2021-02-22 21:18 UTC, cuducos commented on raizama/core/migrations/0013_auto_20210219_1503.py
> +# Generated by Django 3.1.6 on 2021-02-19 18:03
Podemos combinar de **sempre** dar nomes às migrações?

- dar nome às migrações nos ajuda a ser mais objetivos no tamanho da alteração propostas
- migrações com nomes são mais explícitas sobre o que está sendo alterado

Caso interesse, meu fluxo de trabalho nesse ponto é:

1. Ver o que uma migração vai fazer **sem** gerá-la: `python manage.py makemigrations --dryrun`
2. Criar a migração com um nome significativo: `python manage.py makemigrations -n nome_da_minha_migração`

2021-02-22 21:18 UTC, cuducos commented on raizama/core/migrations/0015_EcologicalPractices.py
> +# Generated by Django 3.1.6 on 2021-02-20 19:06
Pela ]PEP8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) o nome dessa migração deveria ser `0015_ecological_practices.py`. Mas isso não me diz exatamente o que ela faz. Que tal `0015_creates_ecological_practices_model.py`?

2021-02-22 21:18 UTC, cuducos commented on raizama/core/models.py
> +    employees = models.CharField("Funcionários", max_length=150)
Se não vamos usar esses campos agora, não vamos criar. Adicionar agora é só criar um risco de dor de cabeça para quando, por exemplo, tivermos que migrar esses `CharField`s para um modelo relacionado.

2021-02-22 21:18 UTC, cuducos commented on raizama/core/models.py
>      cnpj = models.CharField(max_length=40, blank=True, null=True)
Um CNPJ tem 14 dígitos, 18 com a formatação. Pq `max_length=40`?

2021-02-22 21:18 UTC, cuducos commented on raizama/core/models.py
> +    site = models.CharField("Site", max_length=150)
Pq não `URLfield`?

2021-02-22 21:18 UTC, cuducos commented on raizama/core/models.py
> +    facebook = models.CharField("Facebook", max_length=150)
Pq não `URLfield`?

2021-02-22 21:18 UTC, cuducos commented on raizama/core/models.py
>      create_at = models.DateTimeField(default=timezone.now)
`default=timezone.now` não é a abordagem correta aqui (pois permite edição), o correto seria [`auto_now_add`](https://docs.djangoproject.com/en/2.2/ref/models/fields/#django.db.models.DateField.auto_now_add).

2021-02-22 21:18 UTC, cuducos commented on raizama/core/tests.py
> +from raizama.core.models import Organization
Precisamos criar arquivos de teste separados para organizar a casa:
- [ ] crie o diretório `raizama/core/tests/`
- [ ] crie o arquivo (vazio) `raizama/core/tests/__init__.py`
- [ ] dividir o arquivo atual `raizama/core/tests.py` em módulos por tópico (normalmente _objeto_ e _camada_), por exemplo: `raizama/core/tests/test_home_view.py`, `raizama/core/tests/test_organization_model.py`, `raizama/core/tests/test_search_view.py`, `raizama/core/tests/test_search_form.py`

2021-02-22 21:18 UTC, cuducos commented on raizama/core/tests.py
> +        self.assertTrue(Organization.objects.exists())
Esse teste apenas verifica se `Organization.objects.create(…)` (linha 94) funciona. Isso é testar o Django. Não precismaos testar o Django, precisamos testar código da nossa aplicação apenas ; )

2021-02-22 21:18 UTC, cuducos commented on raizama/core/views.py
>                                           ecological_practices=ecological_practices)
Esse trecho pode ser simplificado com:

```python
    organizations = Organization.objects.all()
    if any((search, location, ecological_practices)):
        organizations = organizations.filter(
            name__icontains=search,
            city__icontains=location.lower(),
            ecological_practices=ecological_practices,
        )

```

2021-02-23 12:07 UTC, jocsakesley commented on raizama/core/migrations/0013_auto_20210219_1503.py
> +# Generated by Django 3.1.6 on 2021-02-19 18:03
Ok. Para as próximas migrações irei seguir o fluxo sugerido.

2021-02-23 12:13 UTC, jocsakesley commented on raizama/core/models.py
> +    employees = models.CharField("Funcionários", max_length=150)
Campos removidos.

2021-02-23 12:44 UTC, jocsakesley commented on raizama/core/models.py
>      cnpj = models.CharField(max_length=40, blank=True, null=True)
Campo CNPJ alterado para ```max_length = 18```

2021-02-23 12:50 UTC, jocsakesley commented on raizama/core/migrations/0015_EcologicalPractices.py
> +# Generated by Django 3.1.6 on 2021-02-20 19:06
Arquivo renomeado para o padrão sugerido.

2021-02-23 12:51 UTC, jocsakesley commented on raizama/core/admin.py
> +from .models import Organization, EcologicalPractices
Alterado para o padrão de imports com nomes absolutos.

2021-02-23 16:22 UTC, cuducos requested changes
Acabei de lembrar que implementamos testes nesse PR, mas não documentamos isso no `README.md` — precisamos documentar : )

2021-02-24 14:30 UTC, cuducos requested changes

2021-02-24 14:30 UTC, cuducos commented on raizama/core/models.py
> -        choices=ECO_PRACTICES,
Já que não utilizamos mais a constante `ECO_PRACTICES`, podemos excluí-la de [`raizama/__init__.py`](https://github.com/jocsakesley/raizama/blob/053a260aa1b70acdbddf434e09f401f37cc0ef84/raizama/__init__.py#L1-L8), não?

2021-02-24 19:45 UTC, jocsakesley reviewed
> Acabei de lembrar que implementamos testes nesse PR, mas não documentamos isso no `README.md` — precisamos documentar : )

Comando de teste adicionado ao README

2021-02-24 20:22 UTC, cuducos approved these changes

2021-02-24 20:39 UTC, merged