AWS S3 configuration
jocsakesley/raizama pull request #27
Opened 2021-02-25 18:20 UTC by jocsakesley

Instalação de dependências com poetry;
Adição de variáveis de ambiente para acesso ao bucket S3 em settings.py.

2021-02-25 20:51 UTC, cuducos commented on pyproject.toml
> +boto3 = "^1.17.15"
Essa não é a maneira correta de instalar essas dependências. Na verdade, dependemos do `django-storage` e ele tem um _extra_ que utilizamos que é o `boto3` (e, que [só por acaso, bate com o nome de um _pip-installable_](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies)) — ou seja, Raizama não depende diretamente de `boto3` então `boto3` não deve estar listada como dependência.

Para corrigir, primeiro remova ambos:

```console
$ poetry remove boto3
$ poetry remove django-storages
```

Depois instale o Django Storages com o _extra_:

```console
$ poetry add "django-storage[boto3]"
```

2021-02-25 20:51 UTC, cuducos commented on raizama/settings.py
> +
A gente precisa dessa linha extra em branco aqui, formando duas linhas em branco?

2021-02-25 20:54 UTC, cuducos requested changes

2021-02-25 20:54 UTC, cuducos commented on raizama/settings.py
> +    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
Três coisas:

* Para que `DEV` se já temos `DEBUG`? Qual seria a diferença nos casos de uso de um e de outro?
* Pq remover o `MEDIA_URL`? Ela atrapalha o Whitenoise em produção de alguma forma?
* Pq usar um `if` se usamos o `python-decouple` justamente para desacoplar configuração de código aplicação?

2021-02-26 10:34 UTC, jocsakesley commented on pyproject.toml
> +boto3 = "^1.17.15"
Procedimentos aplicados.

2021-02-26 10:35 UTC, jocsakesley commented on raizama/settings.py
> +
Linha removida

2021-02-26 10:39 UTC, jocsakesley commented on raizama/settings.py
> +    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
- Condicional substituída por ```DEBUG```;
- ```MEDIA_URL``` permanece com ```DEBUG=True```;
- O ```if``` é para evitar o ```MEDIA_URL``` junto com as variáveis de conexão ao storage AWS.

2021-02-26 11:29 UTC, cuducos commented on raizama/settings.py
> +    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
> O if é para evitar o MEDIA_URL junto com as variáveis de conexão ao storage AWS.

Mas qual o efeito de *não* evitar o MEDIA_URL com as variáveis de conexão da AWS? Isso tu não respondeu.

2021-02-26 11:35 UTC, cuducos commented on raizama/settings.py
> +    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
E, outra coisa, como eu disse, vc **não** precisa do `if` — o Python Decouple já resolve isso desacoplando configuração do código.

Se existirem variáveis da AWS, o `config` as carrega, senão ele só deixa `None` no lugar e segue o jogo sem lógica para resolver configuração.

2021-02-26 12:15 UTC, jocsakesley commented on raizama/settings.py
> +    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
Verifiquei que não haveria impacto do ```MEDIA_URL``` com as variáveis da AWS, precisando apenas definir valores default para elas.

2021-02-26 13:42 UTC, cuducos commented
Fixes #22

2021-02-26 13:54 UTC, cuducos requested changes
Creio que ainda falta, para podermos dar o _merge_:

- [x] Remover o _commit_ 3a75be1 pois ele não tem a ver com o propósito do PR (explico mais a seguir)
- [ ] Adicionar as novas variáveis do `settings.py` na documentação (`README.md`, por exemplo)
- [x] Resolver conflitos (tb falo mais a seguir)
- [x] Resolver questões do Prospector (instruções estão no `README.md`)
- [ ] Resolver questões do Black (instruções estão no `README.md`)

**Remover um _commit_ não relacionado**

Existem algumas maneiras de fazer isso e dependendo da situação, uma ou outra pode ser mais aocnselhada. Por exemplo, se o código já está na _branch_ principal, `git revert` normalmente é a melhor opção. Como esse não é o caso, podemos _reescrever a história de commits_ com o `git rebase`.

_Se você quiser “guardar” esse commig em outra _branch_ primeiro

```console
$ git checkout main  # voltar para branch principal
$ git pull origin main  # se certifar de que ela está atualizada
$ git checkout -b <BRANCH NAME>  # criar, a partir da branch principal atualizada, uma outra branch
$ git cherry-pick 3a75be1
```

_Reescrevendo a história dos commits_

```console
$ git checkout storage
$ git rebase -i 3a75be1^1
```

Substituir a palavra antes de `3a75be1` por `drop`. Salvar e sair do editor. Depois disso é só fazer um `pit push origin storage --force` (precisa do _force_ pois agora as branchs não compartilham um passado igual, então temos que sobrescrever a branch remota).

**Conflitos**

Eu recomendo resolver os conflitos manualmente do `pyproject.toml` e depois excluir e gerar novamente o `poetry.lock` com `poetry.lock`.

2021-02-26 13:54 UTC, cuducos commented on requirements.txt
> -
Algum motivo específico para excluir essas linhas?

2021-02-26 14:12 UTC, jocsakesley commented on requirements.txt
> -
Não, o novo ```requirements.txt``` foi gerado automaticamente com ```poetry export -f requirements.txt --output requirements.txt```

2021-02-26 14:16 UTC, cuducos commented on requirements.txt
> -
Sim, mas o que entra ou não num _commit_ é você que escolhe, e você pode escolher linha-a-linha. Nesse caso eu geraria o `requirements.txt` automaticamente como vc fez, mas não adicionaria a parte que remove esse cabeçalho.

Dê uma olhada no comando `git add requirements.txt -p`, acho o help dele bem legal. Uso ele para comitar apenas os trechos relevantes, depois descarto o que não quero (as linhas do cabeçalho) com `git checkout requirements.txt`.

Se não conseguir, me dê um alô que pareamos nisso!

2021-02-27 17:44 UTC, jocsakesley commented on requirements.txt
> -
Pendências resolvidas.

2021-03-01 13:48 UTC, cuducos commented
Do _roadmap_ anterior, desmarquei três coisas que **não** estavam feitas, ok?

O _commit_ que tem que ser removido ainda está no PR:

![Pasted_Image_2021-03-01__8_46_AM](https://user-images.githubusercontent.com/4732915/109505442-992e4300-7a6a-11eb-81d0-3ef72c123991.png)

Ainda existem conflitos:

![Pasted_Image_2021-03-01__8_47_AM](https://user-images.githubusercontent.com/4732915/109505568-ba8f2f00-7a6a-11eb-8323-c6f527d4a131.png)

E o código ainda tem questões levantadas pelo Prospector a serem resolvidas:

```console
$ poetry run prospector
Messages
========

raizama/core/models.py
  Line: 42
    pylint: invalid-name / Variable name "x" doesn't conform to snake_case naming style (col 12)
  Line: 46
    pylint: no-self-use / Method could be a function (col 4)
  Line: 48
    pylint: bad-str-strip-call / Suspicious argument in str.strip call (col 15)

raizama/wsgi.py
  Line: 13
    pylint: import-error / Unable to import 'dj_static'



Check Information
=================
         Started: 2021-03-01 08:44:17.678948
        Finished: 2021-03-01 08:44:21.001520
      Time Taken: 3.32 seconds
       Formatter: grouped
        Profiles: .prospector.yaml, strictness_veryhigh, no_doc_warnings, no_member_warnings, no_test_warnings
      Strictness: from profile
  Libraries Used: django
       Tools Run: dodgy, mccabe, pep8, profile-validator, pyflakes, pylint
  Messages Found: 4
```

2021-03-01 13:49 UTC, cuducos commented on README.md
> +Para executar esse projeto em produção, com `DEBUG=False`, adicione no no arquivo `.env` as seguintes variáveis de ambiente, para persistir os arquivos de mídia no storage S3 da AWS:
O `.env` nem sempre é utilizado em produção. No Heroku, por exemplo, criamos variáveis de ambiente e não tem arquivo `.env` envolvido : )

2021-03-01 16:37 UTC, cuducos commented
Mais duas questões depois desse `git push --force`:

* Qual a função de 3a47f82 nesse PR?
* Qual a função de 84d8081 e 1f3385f nesse PR? A gente já não tinha Gunicorn?

2021-03-01 16:40 UTC, cuducos commented on requirements.txt
> -
Algum motivo para estarmos excluindo essas linhas?

2021-03-01 16:41 UTC, cuducos commented on raizama/settings.py
> +DEFAULT_FILE_STORAGE = config("DEFAULT_FILE_STORAGE", default='django.core.files.storage.FileSystemStorage')
Essa linha com certeza não passa no `poetry run black . --check` ; )

2021-03-01 16:47 UTC, jocsakesley commented on requirements.txt
> -
As linha estão lá, corrigi logo que percebi.

2021-03-01 16:50 UTC, jocsakesley commented
> Mais duas questões depois desse `git push --force`:
> 
> * Qual a função de [3a47f82](https://github.com/jocsakesley/raizama/commit/3a47f8255a56d65a4bda36dfbc6915ede96a92d7) nesse PR?
> * Qual a função de [84d8081](https://github.com/jocsakesley/raizama/commit/84d8081c0083cf0b4ced971413b5fb5af9afc541) e [1f3385f](https://github.com/jocsakesley/raizama/commit/1f3385fec6f9329292a4212d02055c75d6ada872) nesse PR? A gente já não tinha Gunicorn? Se não, isso é assunto para outra _issue_ e outro PR.

*[3a47f82] foi adicionado sozinho pelo merge.
*O Gunicorn não estava nas dependencias e eu precisava pro deply no Heroku.

2021-03-01 16:53 UTC, cuducos commented
> 3a47f82 foi adicionado sozinho pelo merge.

Isso responde _como_ ele veio parar aqui, mas não me diz sobre como ele contribui para _AWS S3 configuration_.

Então, pergunto novamente: qual a função de _alinhar items no HTML_ (mensagem do _commit_) em _configurar o S3_ (título do PR) para _armazenamento_ (nome da _branch_)?

2021-03-01 17:00 UTC, cuducos commented
> O Gunicorn não estava nas dependencias e eu precisava para o deploy no Heroku.

Como eu disse: isso é assunto para outra issue e outro PR.

Pode abrir outra _issue_, criar outro PR para resolver isso — já que não tem a ver com configfurar S3 ou com armazenamento, não cabe nem nesse PR nem nessa _branch_.

2021-03-01 17:04 UTC, cuducos commented
> Pode abrir outra issue, criar outro PR para resolver isso — já que não tem a ver com configfurar S3 ou com armazenamento, não cabe nem nesse PR nem nessa branch.

Isso pode parecer *mais* trabalho, mas não é.
A falta do Gunicorn quebra a producão. Esse PR está em revisão há 4 dias.
É bem mais rápido resolver a questão do Gunicorn em outro PR, muito mais simples do que esse PR, do que embutir ele nessa discussão de dias…

2021-03-01 17:51 UTC, cuducos commented on pyproject.toml
> +
Precisamos dessa linha em branco duplicada?

```suggestion

```

2021-03-02 13:00 UTC, jocsakesley commented on README.md
> +Para executar esse projeto em produção, com `DEBUG=False`, adicione no no arquivo `.env` as seguintes variáveis de ambiente, para persistir os arquivos de mídia no storage S3 da AWS:
Documentação revisada (f18f43b)

2021-03-02 19:45 UTC, cuducos commented on raizama/core/templates/core/search.html
> -
Qual a relação dessa linha removida com esse PR/branch?

2021-03-02 19:45 UTC, merged